/* AUTO-GENERATED by scripts/build-themes.mjs — do not edit by hand */
import type { ThemeListItem, ThemeManifest } from "./_types";
import { FALLBACK_THEME_ID } from "./_types";

export const THEME_MANIFESTS: ThemeManifest[] = [
  {
    "id": "aurora",
    "name": "Aurora",
    "nameZh": "极光",
    "description": "Vivid cyan–violet accent with soft glow",
    "version": 1,
    "tokensFile": "tokens.css",
    "features": {
      "blur": false,
      "gradientBg": true,
      "customFonts": false
    }
  },
  {
    "id": "base",
    "name": "Base",
    "nameZh": "基础",
    "description": "Default clean theme",
    "version": 1,
    "tokensFile": "tokens.css",
    "features": {
      "blur": false,
      "gradientBg": true,
      "customFonts": false
    }
  },
  {
    "id": "glass",
    "name": "Glass",
    "nameZh": "玻璃",
    "description": "Frosted cards, soft gradient backdrop",
    "version": 1,
    "tokensFile": "tokens.css",
    "features": {
      "blur": true,
      "gradientBg": true,
      "customFonts": false
    }
  },
  {
    "id": "minimal",
    "name": "Minimal",
    "nameZh": "极简",
    "description": "Low-chrome, tight spacing, monochrome accent",
    "version": 1,
    "tokensFile": "tokens.css",
    "features": {
      "blur": false,
      "gradientBg": false,
      "customFonts": false
    }
  },
  {
    "id": "old",
    "name": "Old",
    "nameZh": "旧版",
    "description": "Pre-Next.js Hono UI look (indigo SaaS card, 14px radius, soft radial glow)",
    "version": 1,
    "tokensFile": "tokens.css",
    "features": {
      "blur": false,
      "gradientBg": true,
      "customFonts": false
    }
  }
] as ThemeManifest[];

export const THEME_IDS: string[] = THEME_MANIFESTS.map((m) => m.id);

export function listThemes(): ThemeListItem[] {
  return THEME_MANIFESTS.map((m) => ({
    id: m.id,
    name: m.name,
    nameZh: m.nameZh,
    description: m.description || "",
    features: {
      blur: Boolean(m.features?.blur),
      gradientBg: Boolean(m.features?.gradientBg),
      customFonts: Boolean(m.features?.customFonts),
    },
  }));
}

export function getTheme(id: string | undefined | null) {
  const found = THEME_MANIFESTS.find((m) => m.id === id);
  return found ?? THEME_MANIFESTS.find((m) => m.id === FALLBACK_THEME_ID)!;
}

export function resolveThemeId(id: string | undefined | null, siteDefault?: string | null): string {
  if (id && THEME_IDS.includes(id)) return id;
  if (siteDefault && THEME_IDS.includes(siteDefault)) return siteDefault;
  return FALLBACK_THEME_ID;
}

export { FALLBACK_THEME_ID };
