/* AUTO-GENERATED by scripts/build-themes.mjs — do not edit by hand */
import type { ThemeListItem, ThemeManifest } from "./_types";
import { FALLBACK_THEME_ID } from "./_types";

export const THEME_MANIFESTS: ThemeManifest[] = [
  {
    "id": "anthropic",
    "name": "Anthropic Art",
    "nameZh": "Anthropic 插画风",
    "description": "Flat illustration palette: oat page, ivory card, clay accent, near-black ink",
    "version": 1,
    "tokensFile": "tokens.css",
    "features": {
      "blur": false,
      "gradientBg": false,
      "customFonts": true
    }
  },
  {
    "id": "apple",
    "name": "Apple",
    "nameZh": "Apple 风格",
    "description": "Apple.com-inspired marketing UI: cool gray canvas, SF stack, blue primary CTA + pill links (unofficial)",
    "version": 2,
    "tokensFile": "tokens.css",
    "features": {
      "blur": true,
      "gradientBg": false,
      "customFonts": true
    }
  },
  {
    "id": "base",
    "name": "Aurora",
    "nameZh": "极光",
    "description": "Aurora clean theme",
    "version": 1,
    "tokensFile": "tokens.css",
    "features": {
      "blur": false,
      "gradientBg": true,
      "customFonts": false
    }
  },
  {
    "id": "hono-old",
    "name": "Hono Old",
    "nameZh": "Hono 旧版",
    "description": "UI 重构前 Hono 前台：靛蓝强调、14px 圆角、径向光晕、居中链接按钮",
    "version": 1,
    "tokensFile": "tokens.css",
    "features": {
      "blur": false,
      "gradientBg": true,
      "customFonts": false
    }
  },
  {
    "id": "minimal",
    "name": "Minimal",
    "nameZh": "极简",
    "description": "Low-chrome, tight spacing, monochrome accent",
    "version": 1,
    "tokensFile": "tokens.css",
    "features": {
      "blur": false,
      "gradientBg": false,
      "customFonts": false
    }
  },
  {
    "id": "nodeseek",
    "name": "NodeSeek",
    "nameZh": "NodeSeek",
    "description": "Modern Chinese tech-forum UI: cool-gray canvas, soft grid, solid cards, 1px borders, teal accent (unofficial)",
    "version": 1,
    "tokensFile": "tokens.css",
    "features": {
      "blur": false,
      "gradientBg": false,
      "customFonts": false
    }
  },
  {
    "id": "qtcool",
    "name": "QT Cool",
    "nameZh": "晴辰酷",
    "description": "Neo-brutalism à la qt.cool: cream grid, hard offset shadow, thick ink borders, blue #007AFF CTAs (unofficial)",
    "version": 1,
    "tokensFile": "tokens.css",
    "features": {
      "blur": false,
      "gradientBg": false,
      "customFonts": false
    }
  }
] as ThemeManifest[];

export const THEME_IDS: string[] = THEME_MANIFESTS.map((m) => m.id);

export function listThemes(): ThemeListItem[] {
  return THEME_MANIFESTS.map((m) => ({
    id: m.id,
    name: m.name,
    nameZh: m.nameZh,
    description: m.description || "",
    features: {
      blur: Boolean(m.features?.blur),
      gradientBg: Boolean(m.features?.gradientBg),
      customFonts: Boolean(m.features?.customFonts),
    },
  }));
}

export function getTheme(id: string | undefined | null) {
  const found = THEME_MANIFESTS.find((m) => m.id === id);
  return found ?? THEME_MANIFESTS.find((m) => m.id === FALLBACK_THEME_ID)!;
}

export function resolveThemeId(id: string | undefined | null, siteDefault?: string | null): string {
  if (id && THEME_IDS.includes(id)) return id;
  if (siteDefault && THEME_IDS.includes(siteDefault)) return siteDefault;
  return FALLBACK_THEME_ID;
}

export { FALLBACK_THEME_ID };
