/**
 * Sync src/styles/app.css → src/styles/app.css.ts (string export for SSR).
 * Run after editing app.css: node scripts/sync-css.mjs
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const css = readFileSync(join(root, "src/styles/app.css"), "utf8");
const out = `/** Inlined app stylesheet for SSR (no extra HTTP request). Auto-generated by scripts/sync-css.mjs — edit app.css then re-run. */\nexport const appCss = ${JSON.stringify(css)};\n`;
writeFileSync(join(root, "src/styles/app.css.ts"), out, "utf8");
console.log("Synced src/styles/app.css.ts");
